#!/usr/bin/env bash

# To encrypt an env var value:
#   bash .secrets VAR_NAME VALUE >> .secrets
#
# To encrypt a file:
#   bash .secrets FILENAME >> .secrets
#
# To decrypt secrets and restore env vars + files:
#   export `bash .secrets`

if [ -z "$SECRET_KEY" ]; then
  >&2 echo "You need to have SECRET_KEY set"
  exit 1
fi
PASS="pass:$SECRET_KEY"

if [ -n "$1" ]; then
  secretName="$1"
  secretType="var"
  valueCmd="echo -n $2"
  if [ -z "$2" ]; then
    if [ ! -f "$secretName" ]; then
      >&2 echo "Empty secret value."
      exit 1
    fi
    secretType="file"
    valueCmd="cat $1"
  fi

  encoded=$($valueCmd | openssl enc -e -des3 -base64 -A -pass "$PASS" -pbkdf2)
  echo "$secretType \"$secretName\" \"$encoded\""
  exit 0
fi

var() {
  echo -n "$1="
  echo "$2" | openssl enc -d -des3 -base64 -pass "$PASS" -pbkdf2 || exit 1
  echo ""
}

file() {
  echo "$2" | openssl enc -d -des3 -base64 -pass "$PASS" -pbkdf2 > "$1"
}

# SECRETS
